# Generated by Django 4.1.7 on 2023-06-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='username',
            new_name='user',
        ),
    ]
