# Generated by Django 4.1.7 on 2023-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_rename_username_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='premium',
            field=models.BooleanField(default=1),
        ),
    ]
