# Generated by Django 4.1.7 on 2023-05-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None, null=True, verbose_name='Fecha de conversacion')),
                ('conversacion', models.CharField(max_length=3000, verbose_name='conversacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None, null=True, verbose_name='Fecha de pregunta')),
                ('pregunta', models.CharField(max_length=300, verbose_name='pregunta')),
                ('respuesta', models.CharField(max_length=300, verbose_name='respuesta')),
                ('id_conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publica.conversacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
